### ISSUE TITLE
Rotorz Conflicting if already in project

### ISSUE THREAD

**Issue by TarasOsiris** [PhannGor/unity3d-rainbow-folders#14]
https://www.reddit.com/r/Unity3D/comments/4oifbv/custom_icons_for_folders_in_project_view_easy/d4eqdbr

> This is awesome! One request, please move Rotorz's Reorderable List into a subfolder of your main folder, as well as change the namespace so it doesn't conflict with any existing installs of Rotorz's plugins.

**Comment by shayded-exe** [comment]
Hey that's me!

To add to this, I have Rotorz Tile System installed which includes a copy of Reorderable List in Rotorz/Common/, which uses the space Rotorz.Common.ReorderableList, but the newer versions use only Rotorz.ReorderableList. Having both in one project breaks compilation.

For now, I've just worked around it by editing your source to use the Rotorz.Common.ReorderableList namespace. Not sure what the best permanent fix would be.

**Comment by Borod4r** [comment]
Changed namespace for Rotorz reorderable list, to avoid conflicts with existing installs of Rotorz plugins.

b3e3a718f5c7af422dd4740d67052bb4867d414a
