### ISSUE TITLE
Folder Template?

### ISSUE THREAD

**Issue by ninpl** [PhannGor/unity3d-rainbow-folders#15]

**Comment by Borod4r** [comment]
Folder template?

```
          (__)
          (@o)
   /-------\/
  / |     ||
 *  ||----||
    ^^    ^^
```

**Comment by TarasOsiris** [comment]
Please describe the issue in more detail :)

**Comment by ninpl** [comment]
Sorry, I did not want my bad English is noticed.

You have some template (PSD/AI) to create new icons based on default?

**Comment by Borod4r** [comment]
Yep, i have .AI file with default folder template, will add it to repo in few days.

P.S. Don't worry about your English, we're not native speakers also ;)

**Comment by ninpl** [comment]
I'm glad. ;D
