### ISSUE TITLE
Null pointer

### ISSUE THREAD

**Issue by purepure** [PhannGor/unity3d-rainbow-folders#19]
Hey guy!
This plugin is pretty cool, but when I tried, it throw error. I used in unity 5.3. It is really cool if you can fix it

I just drag&drop your project into mine, but it seem not work. Could you please guide me how to integrate?
Thank

ArgumentNullException: Argument cannot be null.
Parameter name: source
System.Linq.Check.SourceAndPredicate (System.Object source, System.Object predicate)
System.Linq.Enumerable.Single[RainbowColorFolder](IEnumerable`1 source, System.Func`2 predicate)
Borodar.RainbowFolders.Editor.FolderColorsStorage.GetIconsByColor (FolderColors color) (at Assets/Plugins/RainbowFolder/RainbowFolders/Editor/Menu/Colors/FolderColorsStorage.cs:71)
Borodar.RainbowFolders.Editor.RainbowFoldersProjectContextMenu.Colorize (FolderColors color) (at Assets/Plugins/RainbowFolder/RainbowFolders/Editor/Menu/RainbowFoldersProjectContextMenu.cs:113)
Borodar.RainbowFolders.Editor.RainbowFoldersProjectContextMenu.Red () (at Assets/Plugins/RainbowFolder/RainbowFolders/Editor/Menu/RainbowFoldersProjectContextMenu.cs:63)

**Comment by TarasOsiris** [comment]
Hello @purepure can you check if you have "Editor Default Resources" folder in the root of your project with Rainbow Folder Settings?

**Comment by Borod4r** [comment]
This is how it should look:
![Editor Default Resources](https://s16.postimg.org/4efjp9fo5/Cropper_Capture_5.png)

**Comment by purepure** [comment]
Sorry for the late delay. It is my failed when missing that folder. Thank for your reply

Great library!
