### ISSUE TITLE
In Unity 5.5.0b6 small icons are shifted

### ISSUE THREAD

**Issue by TarasOsiris** [PhannGor/unity3d-rainbow-folders#23]
Looks like Unity changed the drawing area for icon, intentionally or accidentally. The white area shows the new draw are

<img width="211" alt="unity_5_5_0b6__64bit__-_untitled_-_rainbow_-_pc__mac___linux_standalone__opengl_4_1_" src="https://cloud.githubusercontent.com/assets/3141378/19470272/14e8ab38-951f-11e6-8668-6fe5bbd9dc1b.png">

**Comment by TarasOsiris** [comment]
https://github.com/PhannGor/unity3d-rainbow-folders/pull/24 partially fixes the problem

**Comment by Borod4r** [comment]
Fixed for both small and large icons: 2cfbbba
