### ISSUE TITLE
ALT+CLICK doesn't work with some other assets

### ISSUE THREAD

**Issue by Demigiant** [PhannGor/unity3d-rainbow-folders#25]
ALT+CLICK doesn't work with some assets that eat the ALT event. Implementing also the right-click context menu would solve this for projects that contain other ALT-eating assets.

P.S. Rainbow Folders is awesome! Cheers :)

**Comment by Borod4r** [comment]
Thanks for pointing this out, will fix ASAP.

**Comment by Borod4r** [comment]
Added back the context menu to duplicate all functionality in case ALT event doesn't work: 5f3e8d5

**Comment by Borod4r** [comment]
Probably, I will add some option to select key modifier in near future. It would be better solution in case you have keybinding conflicts with other assets.
